name: Check Terraform

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  check:
    uses: Kokodoki/.github/.github/workflows/check-terraform.yml@v1 # Reemplazar con el ultimo tag disponible
    with:
      working-directory: infra/
      terraform-version: "1.9.0"
